# Generated by Django 5.1.6 on 2025-03-06 01:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='resume',
        ),
        migrations.AddField(
            model_name='applicant',
            name='available_days',
            field=models.CharField(default='Please choose', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='cover_letter',
            field=models.TextField(default='No cover letter provided'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicant',
            name='desired_hourly_wage',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='applicant',
            name='employment_type',
            field=models.CharField(choices=[(None, '--Please choose--'), ('ft', 'Full-time'), ('pt', 'Part-time'), ('contract', 'Contract work')], default='ft', max_length=10),
        ),
        migrations.AddField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='applicant',
            name='start_date',
            field=models.DateField(blank=True, help_text='The earliest date you can start working.', null=True, validators=[jobs.models.validate_future_date]),
        ),
        migrations.AddField(
            model_name='applicant',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='website',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(help_text='A valid email address.', max_length=254),
        ),
        migrations.AddField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
