# Generated by Django 5.1.6 on 2025-03-11 18:49

import djangojokes.storage_backends
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_applicant_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(storage=djangojokes.storage_backends.PublicMediaStorage(), upload_to=jobs.models.avatar_saved)),
            ],
        ),
    ]
