# Generated by Django 5.1.6 on 2025-03-12 16:56

import djangojokes.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_myaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccount',
            name='avatar',
            field=models.ImageField(storage=djangojokes.storage_backends.PublicMediaStorage(), upload_to='avatar'),
        ),
    ]
