# Generated by Django 5.1.6 on 2025-03-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_myaccount_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAccount',
        ),
    ]
