# Generated by Django 5.1.6 on 2025-03-12 17:15

import djangojokes.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_delete_myaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='avatar',
            field=models.ImageField(blank=True, storage=djangojokes.storage_backends.PublicMediaStorage(), upload_to='avatars/'),
        ),
    ]
