# Generated by Django 5.1.6 on 2025-03-02 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0005_alter_joke_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
