# Generated by Django 5.1.6 on 2025-03-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0007_tag_joke_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
    ]
