# Generated by Django 5.1.6 on 2025-03-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0011_jokevote'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.TextField()),
            ],
        ),
    ]
